# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: net.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='net.proto',
  package='kpush.net_proto',
  serialized_pb='\n\tnet.proto\x12\x0fkpush.net_proto\"(\n\x07Wrapper\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x0c\n\x04sign\x18\x02 \x01(\x0c\"g\n\x0fReqUserRegister\x12\r\n\x05\x61ppid\x18\x01 \x01(\x05\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\n\n\x02os\x18\x03 \x01(\t\x12\x12\n\nos_version\x18\x04 \x01(\x05\x12\x12\n\nphone_type\x18\x05 \x01(\t\"+\n\x0fRspUserRegister\x12\x0b\n\x03uid\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\t\"1\n\x12ReqSetAliasAndTags\x12\r\n\x05\x61lias\x18\x01 \x01(\t\x12\x0c\n\x04tags\x18\x02 \x03(\t\"\x11\n\x0f\x45vtNotification\"\x08\n\x06\x45vtMsgB$\n\x18\x63n.vimer.kpush.net_protoB\x08NetProto')




_WRAPPER = _descriptor.Descriptor(
  name='Wrapper',
  full_name='kpush.net_proto.Wrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='kpush.net_proto.Wrapper.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sign', full_name='kpush.net_proto.Wrapper.sign', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=70,
)


_REQUSERREGISTER = _descriptor.Descriptor(
  name='ReqUserRegister',
  full_name='kpush.net_proto.ReqUserRegister',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appid', full_name='kpush.net_proto.ReqUserRegister.appid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='kpush.net_proto.ReqUserRegister.device_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='os', full_name='kpush.net_proto.ReqUserRegister.os', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='os_version', full_name='kpush.net_proto.ReqUserRegister.os_version', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone_type', full_name='kpush.net_proto.ReqUserRegister.phone_type', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=72,
  serialized_end=175,
)


_RSPUSERREGISTER = _descriptor.Descriptor(
  name='RspUserRegister',
  full_name='kpush.net_proto.RspUserRegister',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='kpush.net_proto.RspUserRegister.uid', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='kpush.net_proto.RspUserRegister.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=177,
  serialized_end=220,
)


_REQSETALIASANDTAGS = _descriptor.Descriptor(
  name='ReqSetAliasAndTags',
  full_name='kpush.net_proto.ReqSetAliasAndTags',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alias', full_name='kpush.net_proto.ReqSetAliasAndTags.alias', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='kpush.net_proto.ReqSetAliasAndTags.tags', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=222,
  serialized_end=271,
)


_EVTNOTIFICATION = _descriptor.Descriptor(
  name='EvtNotification',
  full_name='kpush.net_proto.EvtNotification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=273,
  serialized_end=290,
)


_EVTMSG = _descriptor.Descriptor(
  name='EvtMsg',
  full_name='kpush.net_proto.EvtMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=292,
  serialized_end=300,
)

DESCRIPTOR.message_types_by_name['Wrapper'] = _WRAPPER
DESCRIPTOR.message_types_by_name['ReqUserRegister'] = _REQUSERREGISTER
DESCRIPTOR.message_types_by_name['RspUserRegister'] = _RSPUSERREGISTER
DESCRIPTOR.message_types_by_name['ReqSetAliasAndTags'] = _REQSETALIASANDTAGS
DESCRIPTOR.message_types_by_name['EvtNotification'] = _EVTNOTIFICATION
DESCRIPTOR.message_types_by_name['EvtMsg'] = _EVTMSG

class Wrapper(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WRAPPER

  # @@protoc_insertion_point(class_scope:kpush.net_proto.Wrapper)

class ReqUserRegister(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUSERREGISTER

  # @@protoc_insertion_point(class_scope:kpush.net_proto.ReqUserRegister)

class RspUserRegister(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RSPUSERREGISTER

  # @@protoc_insertion_point(class_scope:kpush.net_proto.RspUserRegister)

class ReqSetAliasAndTags(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQSETALIASANDTAGS

  # @@protoc_insertion_point(class_scope:kpush.net_proto.ReqSetAliasAndTags)

class EvtNotification(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVTNOTIFICATION

  # @@protoc_insertion_point(class_scope:kpush.net_proto.EvtNotification)

class EvtMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVTMSG

  # @@protoc_insertion_point(class_scope:kpush.net_proto.EvtMsg)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\030cn.vimer.kpush.net_protoB\010NetProto')
# @@protoc_insertion_point(module_scope)
