# -*- coding: utf-8 -*-

# 命令字
CMD_REGISTER = 1
CMD_LOGIN = 2
CMD_HEARTBEAT = 3
CMD_SET_ALIAS_AND_TAGS = 4
CMD_REMOVE_USER = 5

CMD_NOTIFICATION_RECV = 101
CMD_NOTIFICATION_CLICK = 102

# 事件
EVT_NOTIFICATION = 1001
EVT_MESSAGE = 1002


# 返回码
RET_INVALID_PARAMS = 1
RET_INTERNAL_ERROR = 2
RET_NO_DATA = 3

RET_NOT_LOGIN = 1000
RET_REPEAT_ACTION = 1001  # 重复操作
